#!/bin/bash
# vim: ft=sh:sw=2:ts=2:et
# Installs Foreman nightly using snap-guest

# needed for YUM/RPM scriplets to work correctly
export PATH=$PATH:/usr/bin:/usr/sbin:/bin:/sbin

[ -f /etc/redhat-release ] && OSNV=el$(rpm -q --queryformat '%{RELEASE}' redhat-release-server | awk -F. '{print $1}')
[ -f /etc/fedora-release ] && OSNV=f$(rpm -q --queryformat '%{VERSION}' fedora-release)

setenforce 0
service iptables stop

[ -f /etc/redhat-release ] && yum -y install http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

rpm -q foreman-release || yum -y install http://yum.theforeman.org/nightly/$OSNV/x86_64/foreman-release.rpm
rpm -q foreman-installer || yum -y install ruby puppet foreman-installer

# WORKAROUNDS
# F19
cp /usr/lib/systemd/system/puppetagent.service /etc/systemd/system/puppet.service
# /WORKAROUNDS

# TODO CUSTOM_REPO env variable

mkdir /etc/foreman-installer 2>/dev/null
cat >/etc/foreman-installer/answers.yaml <<EOF
foreman:
  repo: nightly
foreman_proxy:
  repo: nightly
puppet:
  server: true
EOF
echo include foreman_installer | puppet apply -v --modulepath /usr/share/foreman-installer
